name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install Dependencies
      working-directory: ./app
      run: npm install
      
    - name: Run Tests
      working-directory: ./app
      run: |
        npm test -- --coverage --coverageThreshold='{"global":{"statements":50,"branches":50,"functions":50,"lines":50}}'
      continue-on-error: true

    - name: Check Test Coverage
      working-directory: ./app
      run: |
        COVERAGE=$(npm test -- --coverage --coverageThreshold='{"global":{"statements":50,"branches":50,"functions":50,"lines":50}}' 2>&1 | grep -A 4 "All files" | awk 'NR==2 {print $2}' | sed 's/%//')
        if (( $(echo "$COVERAGE >= 50" | bc -l) )); then
          echo "Coverage is above 50% ($COVERAGE%)"
          exit 0
        else
          echo "Coverage is below 50% ($COVERAGE%)"
          exit 1
        fi